### ISSUE TITLE
frontend - plans overview

### ISSUE THREAD

**Issue by AlexanderLeonidasGuenzel** [AlexanderLeonidasGuenzel/easyplan#2]

**Comment by AlexanderLeonidasGuenzel** [comment]
##  value properties

As a user
I want to have an overview of existing working plans.

## Description

- When users start the application they should see an overview with existing working plans. If there is no plan added yet, they see an information text.

## Acceptance criteria

- [x] user see welcome page with text 


## Tasks

- [x] create webpage
- [x] add heading: welcome 
- [x] add heading: working plans
- [x] add text: there are no existing plans
