### ISSUE TITLE
project setup and deployment

### ISSUE THREAD

**Issue by AlexanderLeonidasGuenzel** [AlexanderLeonidasGuenzel/easyplan#4]
##  value properties

As a developer
I want a fullstack project setup with all I need for coding and deployment. 

## Description

- 

## Acceptance criteria

- [x] all workflow action checks passed [Deploy App, Get Logs, Java CI with Maven, Sonar-Frontend, SonarCloud-Backend]
- [x] fullstack project init [backend & frontend modules]
- [x] deployment works
- [x] local dev works

## Tasks

- [x] create spring project
- [x] create backend & frontend modules
- [x] setup code analysis with sonarcloud 
- [x] create database connections to mongodb 
- [x] setup automated deployment 
- [x] setup github repo
