### ISSUE TITLE
backend - post endpoint

### ISSUE THREAD

**Issue by AlexanderLeonidasGuenzel** [AlexanderLeonidasGuenzel/easyplan#6]
##  Value properties

As a developer
I want to add new plan entries.

## Description

- It should be possible to add a new plan via postman. It will be saved in database. Just backend.

## Acceptance criteria

- [x] it is possible to add a plan entry via postman 

## Tasks

- [x] create post endpoint in controller
- [x] create add method in service
