### ISSUE TITLE
frontend - form add plan

### ISSUE THREAD

**Issue by AlexanderLeonidasGuenzel** [AlexanderLeonidasGuenzel/easyplan#7]
##  Value properties

As a user
I want to add new plan entries via webpage input.

## Description

- It should be possible to add a new plan via form-element. It will be saved in database. 

## Acceptance criteria

- [x] it is possible to add a plan entry on webpage

## Tasks

- [x] create html form with input and button
- [x] create datatransfer to backend with axios
